### ISSUE TITLE
Can't run redfishtool.py (in virtualenv?)

### ISSUE THREAD

**Issue by mkhon** [DMTF/Redfishtool#13]
```
(redfishtool-virtualenv) installer@xxx:~$ redfishtool.py 
Traceback (most recent call last):
  File "/home/installer/redfishtool-virtualenv/bin/redfishtool.py", line 4, in <module>
    __import__('pkg_resources').run_script('redfishtool==1.0.0', 'redfishtool.py')
  File "/home/installer/redfishtool-virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/installer/redfishtool-virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/installer/redfishtool-virtualenv/lib/python3.5/site-packages/redfishtool-1.0.0-py3.5.egg/EGG-INFO/scripts/redfishtool.py", line 14, in <module>
  File "/home/installer/redfishtool-virtualenv/bin/redfishtool.py", line 4, in <module>
    __import__('pkg_resources').run_script('redfishtool==1.0.0', 'redfishtool.py')
  File "/home/installer/redfishtool-virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/installer/redfishtool-virtualenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/installer/redfishtool-virtualenv/lib/python3.5/site-packages/redfishtool-1.0.0-py3.5.egg/EGG-INFO/scripts/redfishtool.py", line 14, in <module>
ImportError: cannot import name 'main'
(redfishtool-virtualenv) installer@xxx:~$ python --version
Python 3.5.2
(redfishtool-virtualenv) installer@xxx:~$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2017.4.17)
chardet (3.0.4)
idna (2.5)
pip (9.0.1)
pkg-resources (0.0.0)
redfishtool (1.0.0)
requests (2.17.3)
setuptools (36.0.1)
urllib3 (1.21.1)
wheel (0.30.0a0)
(redfishtool-virtualenv) installer@xxx:~$ 
```

If I rename `$venv/bin/redfishtool.py` to `$venv/bin/redfishtool` all works ok.

The problem is that `$venv/bin/redfishtool.py` is imported by `pkg_resources` and `main()` is searched in there instead of `redfishtool` package.

**Comment by billdodd** [comment]
Thanks for the report. I can confirm the error, and it's not just in virtualenv. When I tested the script previously I must have been executing a local version that had the redfishtool package in the same directory as the script, so didn't see the error.

To fix, I think there are three options:

1. Rename either redfishtool.py or the redfishtool package (dir), so they do not clash.
2. Remove the '.py' from the redfishtool.py script (and move it to a subdir like 'scripts').
3. Similar to (2), keep the existing redfishtool.py in the repo. But create a copy of it in a 'scripts' directory, but without the '.py. suffix. Have the setup.py install the 'scripts/redfishtool' version of the script.

Options 1 & 2 can have some impact to existing refishtool users. I think option 3 minimizes potential impacts.
