### ISSUE TITLE
skip1=False -- SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vincentleephilips** [DMTF/Redfishtool#44]
```
[vincentlee@on-net ~]$ redfishtool -r 10.0.0.2 -u redacted -p redacted Systems examples
Traceback (most recent call last):
  File "/usr/local/bin/redfishtool", line 14, in <module>
    from redfishtool import main
  File "/usr/local/lib/python2.7/site-packages/redfishtool/__init__.py", line 5, in <module>
    from .redfishtoolMain import main
  File "/usr/local/lib/python2.7/site-packages/redfishtool/redfishtoolMain.py", line 21, in <module>
    from .redfishtoolTransport   import RfTransport
  File "/usr/local/lib/python2.7/site-packages/redfishtool/redfishtoolTransport.py", line 723
    def printVerbose(self,v,*argv, skip1=False, printV12=True,**kwargs):
                                       ^
SyntaxError: invalid syntax
```

**Comment by mraineri** [comment]
It looks like you're using Python2.7, but this tool is designed for Python3.X. Could you please try using a newer version of Python?

**Comment by mraineri** [comment]
Closing; the tool does not support Python2.7. Please upgrade your environment to Python3.
